/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/eneo.theme.ts
 * Command: astryx theme build src/theme/eneo.theme.ts --out src/theme/built/eneo.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const eneoTheme: DefinedTheme;
