/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/eneo.theme.ts
 * Command: astryx theme build src/theme/eneo.theme.ts --out src/theme/built/eneo.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/**
 * eneo theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { eneoTheme } from './eneo';
 *   import './eneo.css';
 */
export const eneoTheme = {
  name: 'eneo',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#004595, #52B1FF)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #0B1118)",
    "--color-neutral": "light-dark(#1B1B1F1A, #DFE3E833)",
    "--color-background-surface": "light-dark(#FBFCFF, #191C1F)",
    "--color-background-body": "light-dark(#F0F0F6, #0E1115)",
    "--color-overlay": "light-dark(#1B1B1F66, #191C1F99)",
    "--color-overlay-hover": "light-dark(#1B1B1F0D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#1B1B1F1A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#1B1B1F0D, #191C1F80)",
    "--color-text-primary": "light-dark(#1B1B1F, #DFE3E8)",
    "--color-text-secondary": "light-dark(#454650, #A5ACB6)",
    "--color-text-disabled": "light-dark(#8F909B, #585F68)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#1B1B1F, #DFE3E8)",
    "--color-icon-secondary": "light-dark(#454650, #A5ACB6)",
    "--color-icon-disabled": "light-dark(#8F909B, #585F68)",
    "--color-background-card": "light-dark(#FBFCFF, #191C1F)",
    "--color-background-popover": "light-dark(#FBFCFF, #2E3135)",
    "--color-background-inverted": "light-dark(#1B1B1F, #F9FCFF)",
    "--color-border": "light-dark(#1B1B1F1A, #EDF1F61A)",
    "--color-border-emphasized": "light-dark(#85868F, #626972)",
    "--color-skeleton": "light-dark(#A9AAB5, #414750)",
    "--color-track": "light-dark(#A9AAB5, #414750)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.5rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.6875rem",
    "--font-size-sm": "0.875rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.1875rem",
    "--font-size-xl": "1.4375rem",
    "--font-size-2xl": "1.75rem",
    "--font-size-3xl": "2.0625rem",
    "--font-size-4xl": "2.5rem",
    "--font-size-5xl": "3rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.4286",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.3913",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4737",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.4545",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4737",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.25",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.3",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2121",
    "--font-family-body": "system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Arial, sans-serif",
    "--font-family-heading": "system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Arial, sans-serif",
    "--font-family-code": "ui-monospace, \"SFMono-Regular\", Consolas, monospace",
    "--color-on-error": "light-dark(#FFFFFF, #1A0A0C)",
    "--size-element-lg": "48px",
    "--color-error": "light-dark(#AA181D, #F47B7F)"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "base": {
        "overflowWrap": "anywhere",
        ":focus-visible": {
          "outline": "none"
        }
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      },
      "base": {
        "overflowWrap": "anywhere"
      }
    },
    "text-input": {
      "base": {
        ":focus-within": {
          "outline": "var(--focus-outline-width) var(--focus-outline-style) var(--focus-outline-color)",
          "outlineOffset": "calc(var(--border-width) * -1)",
          "boxShadow": "none"
        }
      }
    },
    "text-area": {
      "base": {
        ":focus-within": {
          "outline": "var(--focus-outline-width) var(--focus-outline-style) var(--focus-outline-color)",
          "outlineOffset": "calc(var(--border-width) * -1)",
          "boxShadow": "none"
        }
      }
    },
    "number-input": {
      "base": {
        ":focus-within": {
          "outline": "var(--focus-outline-width) var(--focus-outline-style) var(--focus-outline-color)",
          "outlineOffset": "calc(var(--border-width) * -1)",
          "boxShadow": "none"
        }
      }
    },
    "selector": {
      "base": {
        ":focus-within": {
          "outline": "var(--focus-outline-width) var(--focus-outline-style) var(--focus-outline-color)",
          "outlineOffset": "calc(var(--border-width) * -1)",
          "boxShadow": "none"
        }
      }
    },
    "typeahead": {
      "base": {
        ":focus-within": {
          "outline": "var(--focus-outline-width) var(--focus-outline-style) var(--focus-outline-color)",
          "outlineOffset": "calc(var(--border-width) * -1)",
          "boxShadow": "none"
        }
      }
    },
    "tokenizer": {
      "base": {
        ":focus-within": {
          "outline": "var(--focus-outline-width) var(--focus-outline-style) var(--focus-outline-color)",
          "outlineOffset": "calc(var(--border-width) * -1)",
          "boxShadow": "none"
        }
      }
    },
    "dropdown-menu-item": {
      "base": {
        ":focus-visible": {
          "outline": "var(--focus-outline-width) var(--focus-outline-style) var(--focus-outline-color)",
          "outlineOffset": "calc(var(--focus-outline-width) * -1)"
        }
      }
    },
    "item": {
      "base": {
        "overflowWrap": "anywhere"
      }
    },
    "slider-control": {
      "base": {
        "minBlockSize": "24px"
      }
    },
    "button": {
      "base": {
        "whiteSpace": "normal",
        "height": "auto",
        "minHeight": "var(--size-element-md)",
        "paddingBlock": "var(--spacing-0-5)"
      },
      "size:sm": {
        "minHeight": "var(--size-element-sm)"
      },
      "size:lg": {
        "minHeight": "var(--size-element-lg)"
      }
    },
    "avatar-fallback": {
      "base": {
        "color": "var(--color-text-primary)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": [
      {
        "when": {
          "pointer": "coarse"
        },
        "value": {
          "tokens": {
            "--size-element-sm": "44px",
            "--size-element-md": "44px",
            "--size-element-lg": "48px"
          },
          "components": {
            "dropdown-menu-item": {
              "base": {
                "minHeight": "44px"
              }
            },
            "selector-option-row": {
              "base": {
                "minHeight": "44px"
              }
            },
            "typeahead-item": {
              "base": {
                "minHeight": "44px"
              }
            },
            "top-nav-heading": {
              "base": {
                "minHeight": "44px"
              }
            },
            "slider-control": {
              "base": {
                "minBlockSize": "44px"
              }
            },
            "collapsible-trigger": {
              "base": {
                "minHeight": "44px"
              }
            }
          }
        }
      }
    ]
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 16,
        "ratio": 1.2
      },
      "body": {
        "family": "system-ui",
        "fallbacks": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Arial, sans-serif"
      },
      "code": {
        "family": "ui-monospace",
        "fallbacks": "\"SFMono-Regular\", Consolas, monospace"
      }
    },
    "color": {
      "accent": [
        "#004595",
        "#52B1FF"
      ],
      "neutralStyle": "neutral",
      "contrast": "standard"
    }
  },

};
